### PR TITLE
add export procedures

### PR DESCRIPTION
**Pull request by jimoibm**
@kadler I added runascii and runclient.

### CODE REVIEW

**Comment by kadler** [comment]
What is using RUNCLIENT?

**Comment by jimoibm** [comment]
@kadler  The code says user's RPG program will call this.

**Comment by kadler** [comment]
Can you point to that?

AFAIK, nothing should be calling runClient externally. They get used by the stored procedure functions as well as xmlmain, but all the XMLSERVICE programs and service programs use static linking so it doesn't need to be exported.

**Comment by jimoibm** [comment]
In the wiki source code, it says so. I guess there might be users calling it.
> rpg-web-services.wiki -- 
* XMLSERVICE/XMLSTOREDP.SRVPGM -- optional custom transport (programmers only)
** if included XMLSERVICE transports do not fill your need, please feel free to create your own (sockets, data queues, ftp, etc.). Multiple entry APIs exist in XMLSERVICE that you may find useful:\\
[@
xmlstoredp.srvpgm - *SRVPGM interface for calls

  Native stored procedure call target (iPLUG4K - iPLUG15M):
     D iPLUG4K         PR             1N   extproc(*CL:'iPLUG4K')
     D pIPC                        1024A
     D pCtl                        1024A
     D pXmlIn                          *
     D pXmlOut                         *

   RPG call target:
     D runClient       PR             1N
     D   pIPCSP                    1024A
     D   pCtl                      1024A
     D   pIClob                        *
     D   szIClob                     10i 0
     D   pOClob                        *
     D   szOClob                     10i 0

   PASE call target (also use RPG when CCSID issues):
     D runASCII        PR             1N
     D   pIPCSP2                       *
     D   szIPCSP2                    10i 0
     D   pCtlSP2                       *
     D   szCtlSP2                    10i 0
     D   pIClob2                       *
     D   szIClob2                    10i 0
     D   pOClob2                       *
     D   szOClob2                    10i 0
     D   ccsidPASE2                  10i 0
     D   ccsidILE2                   10i 0

@]

**Comment by kadler** [comment]
I suspect that nobody is using it, especially since the export id will change every time and they'll have to re-compile. I suggest we remove that one until someone asks for it.

**Comment by kadler** [comment]
FYI, I think you meant to send this PR to IBM/xmlservice, but instead it's going to your personal repo.

**Comment by jimoibm** [comment]
OK. I will remove runclient until some asks for it. My changes is based on change in #36. To make the review easier, I put PR to my repos.

**Pull request closed without merging**
